title: Personal Notes
repository: my1396/my1396.github.io
author:
  name: Menghan Yuan
  email: my1396@nyu.edu

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Online notes for keeping records of things.

# Build settings
markdown: kramdown
# Syntax highlighting
highlighter:
kramdown:
  input: GFM
  syntax_highlighter: rouge

baseurl: /Econ-Study
# Use the following plug-ins
plugins:
  - jekyll-feed       # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag    # output metadata for search engines to better index and display
  - jekyll-pdf-embed  # embed pdf files
  - jekyll-sitemap    # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-scholar    # add references and bibliography
  - jekyll-gist       # embed gist

google_analytics: G-SHRDBGDKKC

# Jekyll-Scholar config
scholar:
  style: apa

# Theme-specific settings
theme: minima
minima:
  skin: auto
  social_links:
    - { platform: github,         user_url: "https://github.com/my1396" }
    - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }

  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }

  #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up. Name the files in the order you want to show on the home page.
#
header_pages:
  - 01_tags.md
  - 02_about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false

